### PR TITLE
Fixed metadata crash for messages

### PR DESCRIPTION
**Pull request by MaherKSantina**

### CODE REVIEW

**Review by dipeshfrollo — APPROVED** [review]

**Review by sincychacko-frollo — APPROVED** [review]

**Review by nickfrollo — CHANGES_REQUESTED** [review]
Can you update Xcodeproj with new version and Readme.md too please?

Otherwise changes looking good! Thanks.

**Comment by MaherKSantina** [comment]
Right totally forgot about this 🤦

**Review by nickfrollo — COMMENTED** [review]
README.md too please? 🙂

**Comment by MaherKSantina** [comment]
Done! 🎉

**Review by nickfrollo — APPROVED** [review]
Wooo! Thanks

**Pull request merged**
